import re

with open('index.html', 'r', encoding='utf-8') as f:
    html = f.read()

tr_map = {
    'lang="en"': 'lang="tr"',
    'Incoming Travel Agency Turkey | Medical Tourism Istanbul': 'Gelen Seyahat Acentesi Türkiye | Sağlık Turizmi İstanbul',
    'Plan Your Trip': 'Seyahatinizi Planlayın',
    'About': 'Hakkımızda',
    'Services': 'Hizmetler',
    'Destinations': 'Destinasyonlar',
    'Team': 'Ekip',
    'Contact': 'İletişim',
    'Your Trusted Partner<br />\n          <em>for Travel in Turkey</em>': 'Türkiye\'deki Güvenilir<br />\n          <em>Seyahat Ortağınız</em>',
    'Incoming tourism &amp; medical health tourism for visitors from the<br class="br-desktop" />\n          Middle East, Gulf region, and beyond — with a smile.': 'Orta Doğu, Körfez bölgesi ve ötesinden gelen ziyaretçiler için<br class="br-desktop" />\n          gelen turizmi ve sağlık turizmi — gülümsemeyle.',
    'Explore Our Services': 'Hizmetlerimizi Keşfedin',
    'Years of Experience': 'Yıllık Deneyim',
    'Tour Operators &amp; Direct': 'Tur Operatörleri ve Doğrudan',
    'Primary Market Specialists': 'Ana Pazar Uzmanları',
    'Established 2005': 'Kuruluş 2005',
    'Over 20 years serving international visitors': 'Uluslararası ziyaretçilere 20 yılı aşkın hizmet',
    'Official TURSAB Member': 'Resmi TÜRSAB Üyesi',
    'License No. A-7468 — Fully certified &amp; regulated': 'Lisans No. A-7468 — Tam sertifikalı ve denetimli',
    'Multilingual Team': 'Çok Dilli Ekip',
    'Support for Gulf &amp; Middle East visitors': 'Körfez ve Orta Doğu ziyaretçilerine destek',
    'Incoming Agency Only': 'Sadece Gelen (Incoming) Acente',
    '100% focused on welcoming visitors to Turkey': 'Türkiye\'ye gelen ziyaretçileri ağırlamaya %100 odaklanmış',
    'Guests Welcomed': 'Ağırlanan Misafir',
    'Countries Served': 'Hizmet Verilen Ülke',
    'Core Specialisations': 'Temel Uzmanlık Alanları',
    'Who We Are': 'Biz Kimiz',
    'Your Smile is<br /><em>Our Mission</em>': 'Gülümsemeniz<br /><em>Misyonumuzdur</em>',
    'Get in Touch': 'İletişime Geçin',
    'Our Core Values': 'Temel Değerlerimiz',
    'Openness &amp; Partnership': 'Açıklık ve Ortaklık',
    'We embrace the values and ideas of our partners and clients.': 'Ortaklarımızın ve müşterilerimizin değerlerini ve fikirlerini benimsiyoruz.',
    'Teamwork at Heart': 'Özünde Ekip Çalışması',
    'Management that leads by collaboration, not hierarchy.': 'Hiyerarşiyle değil, işbirliğiyle yöneten bir anlayış.',
    'Passionate Professionals': 'Tutkulu Profesyoneller',
    'A dedicated team working with skill and genuine care.': 'Beceri ve samimi ilgiyle çalışan özverili bir ekip.',
    'Guests, Not Customers': 'Müşteri Değil, Misafir',
    'Every traveler is treated as a respected guest in our home.': 'Her gezgin evimizde saygın bir misafir olarak ağırlanır.',
    'Attention to Detail': 'Detaylara Dikkat',
    'Maximum care at every step of the journey.': 'Yolculuğun her adımında azami özen.',
    'Guest Satisfaction First': 'Önce Misafir Memnuniyeti',
    'Your happiness is our highest achievement.': 'Mutluluğunuz bizim en büyük başarımızdır.',
    'Always Adapting': 'Daima Uyum Sağlayan',
    'Striving for perfection and adapting to a changing world.': 'Mükemmellik için çabalıyor ve değişen dünyaya uyum sağlıyoruz.',
    'Always Smiling': 'Daima Gülümseyen',
    'A positive spirit — even in challenging situations.': 'Zor durumlarda bile pozitif bir ruh hali.',
    'What We Offer': 'Neler Sunuyoruz',
    'Three Pillars of<br />\n            <em>Expert Service</em>': 'Uzman Hizmetin<br />\n            <em>Üç Temel Direği</em>',
    'We arrange everything from A to Z so international guests can seamlessly arrive and enjoy Turkey.': 'Yurt dışından gelen misafirlerimizin sorunsuz bir şekilde gelip Türkiye\'nin tadını çıkarması için A\'dan Z\'ye her şeyi ayarlıyoruz.',
    'Incoming Tourism &amp; Transportation': 'Gelen Turizm ve Ulaşım',
    'From budget-friendly hotel reservations to luxury custom accommodation, we arrange everything you need to travel to Turkey from abroad. We offer 24/7 comfortable transport with chauffeured luxury vehicles or rent-a-car services, alongside private guided tours with expert local guides.': 'Biz, yurt dışından gelen misafirlerimize yüksek standartlarda hizmet sunan tam yetkili bir seyahat acentesiyiz. Geniş partner ağımız sayesinde, en uygun fiyatlı otel rezervasyonlarından kişiye özel konaklama çözümlerine kadar her bütçeye hitap ediyoruz. Şoförlü lüks araç seçeneklerimiz veya şoförsüz araç kiralama hizmetlerimizle 7/24 konforlu ulaşım sağlıyoruz ve uzman rehberler eşliğinde özel turlar düzenliyoruz.',
    '24/7 VIP Transfers': '7/24 VIP Transferler',
    'Rent-a-car': 'Araç Kiralama',
    'Private Guided Tours': 'Özel Rehberli Turlar',
    'Hotel Reservations': 'Otel Rezervasyonları',
    'Local Guides': 'Yerel Rehberler',
    'Custom Itineraries': 'Özel Güzergahlar',
    'Plan Your Visit': 'Ziyaretinizi Planlayın',
    'Medical &amp; Health Tourism': 'Medikal ve Sağlık Turizmi',
    'We professionally manage your entire medical journey in collaboration with state-of-the-art hospitals. From initial referrals and certified interpretation to VIP accommodation and recovery, we ensure a seamless and dignified experience.': 'Son teknolojiye sahip hastanelerle iş birliği içinde yürüttüğümüz sağlık turizmi ile misafirlerimizin tüm süreçlerini profesyonelce yönetiyoruz.',
    'Hospital Referrals': 'Hastane Yönlendirmeleri',
    'High-Tech Clinic Partners': 'Son Teknoloji Klinik Ortakları',
    'Arabic Interpretation': 'Arapça Tercümanlık',
    'VIP Accompaniment': 'VIP Refakat',
    'Patient Transfers': 'Hasta Transferleri',
    'Recovery Stays': 'İyileşme Konaklamaları',
    'Post-treatment Tours': 'Tedavi Sonrası Turlar',
    'Enquire About Medical Tourism': 'Sağlık Turizmi Hakkında Bilgi Alın',
    'Corporate Events &amp; MICE': 'Kurumsal Etkinlikler ve MICE',
    'For large-scale corporate organizations and international meetings, we provide A-to-Z professional planning and management. Every detail is meticulously planned to ensure your events are executed flawlessly.': 'Büyük katılımlı kurumsal organizasyonlar, uluslararası toplantılar ve her detayı titizlikle planlanmış etkinlikleriniz için A\'dan Z\'ye profesyonel planlama ve yönetim desteği sunuyoruz.',
    'Event Planning': 'Etkinlik Planlama',
    'International Meetings': 'Uluslararası Toplantılar',
    'Corporate Organization': 'Kurumsal Organizasyon',
    'VIP Protocol': 'VIP Protokol',
    'Ground Handling': 'Yer Hizmetleri',
    'Agency Partnerships': 'Acente Ortaklıkları',
    'Group Programs': 'Grup Programları',
    'Trade Rates': 'Ticari Fiyatlar',
    'Start Planning': 'Planlamaya Başlayın',
    'Our primary markets': 'Ana pazarlarımız',
    'Where We Take You': 'Sizi Nereye Götürüyoruz',
    'Discover<br /><em>Turkey</em>': 'Türkiye\'yi<br /><em>Keşfedin</em>',
    'From the vibrant streets of Istanbul to the magical skies of Cappadocia — we know Turkey inside out.': 'İstanbul\'un hareketli sokaklarından Kapadokya\'nın büyülü gökyüzüne — Türkiye\'yi çok iyi tanıyoruz.',
    'Flagship Destination': 'Öncü Destinasyon',
    'Culture, History &amp; the Bosphorus': 'Kültür, Tarih ve Boğaziçi',
    'Imperial palaces, vibrant bazaars, private Bosphorus cruises, and world-class cuisine. The city where East meets West.': 'İmparatorluk sarayları, hareketli pazarlar, özel boğaz turları ve dünya standartlarında mutfak. Doğunun Batı ile buluştuğu şehir.',
    'Discover Istanbul': 'İstanbul\'u Keşfedin',
    'Must-See Wonder': 'Görülmesi Gereken Harika',
    'Balloons &amp; Fairy Chimneys': 'Balonlar ve Peri Bacaları',
    'Rise with the sun in a hot air balloon over otherworldly landscapes. Underground cities, cave hotels, and unique scenery.': 'Başka dünyalara ait manzaralar üzerinde sıcak hava balonuyla güneşle birlikte yükselin. Yeraltı şehirleri, mağara otelleri.',
    'Discover Cappadocia': 'Kapadokya\'yı Keşfedin',
    'Nature &amp; Serenity': 'Doğa ve Huzur',
    'Lakes, Mountains &amp; Thermal Spas': 'Göller, Dağlar ve Termal Kaplıcalar',
    'Peaceful lakeside retreats, thermal spas, and verdant mountain escapes just a short drive from Istanbul.': 'İstanbul\'dan kısa bir sürüş mesafesinde huzurlu göl kenarı inzivaları, termal kaplıcalar ve yemyeşil dağ kaçamakları.',
    'Discover Sapanca': 'Sapanca\'yı Keşfedin',
    'The Green North': 'Yeşil Kuzey',
    'Monasteries &amp; Black Sea Heritage': 'Manastırlar ve Karadeniz Mirası',
    'Ancient monasteries, lush highland plateaus, and the dramatic beauty of the Black Sea coast.': 'Antik manastırlar, yemyeşil yaylalar ve Karadeniz sahilinin dramatik güzelliği.',
    'Discover Trabzon': 'Trabzon\'u Keşfedin',
    'Your Point of Contact': 'İletişim Noktanız',
    'Meet the<br /><em>Team</em>': 'Ekibimizle<br /><em>Tanışın</em>',
    'Real people, always available. Reach out directly to the right person for your needs.': 'Gerçek insanlar, her zaman ulaşılabilir. İhtiyaçlarınız için doğrudan doğru kişiye ulaşın.',
    'Manager': 'Yönetici',
    'Sales': 'Satış',
    'Reservations': 'Rezervasyon',
    'Contact Us': 'Bize Ulaşın',
    'Plan Your<br /><em>Journey to Turkey</em>': 'Türkiye<br /><em>Seyahatinizi Planlayın</em>',
    'Ready to start planning your trip? We handle all requests directly via WhatsApp to ensure you get the fastest, most personalized service.': 'Seyahatinizi planlamaya başlamaya hazır mısınız? En hızlı ve en kişiselleştirilmiş hizmeti almanızı sağlamak için tüm talepleri doğrudan WhatsApp üzerinden karşılıyoruz.',
    'Fast response from our dedicated team': 'Özel ekibimizden hızlı yanıt',
    'Tailored itinerary — no templates': 'Özel güzergah — şablon yok',
    'English, Arabic &amp; Russian support': 'İngilizce, Arapça ve Rusça destek',
    'TURSAB certified — your guarantee': 'TÜRSAB sertifikalı — garantiniz',
    'Message on WhatsApp': 'WhatsApp\'tan Mesaj Gönder',
    'Call': 'Ara',
    'We\'re Online & Ready': 'Çevrimiçiyiz ve Hazırız',
    'Skip the forms and email wait times. Chat directly with our dedicated team on WhatsApp for instant assistance and personalized travel planning.': 'Formları ve e-posta bekleme sürelerini atlayın. Anında yardım ve kişiselleştirilmiş seyahat planlaması için özel ekibimizle doğrudan WhatsApp üzerinden sohbet edin.',
    'Instant Responses': 'Anında Yanıtlar',
    'Personalized Care': 'Kişiselleştirilmiş İlgi',
    'Priority Booking': 'Öncelikli Rezervasyon',
    'Start WhatsApp Chat': 'WhatsApp Sohbetini Başlat',
    'Privacy Policy': 'Gizlilik Politikası',
    'Terms of Service': 'Kullanım Şartları'
}

html_tr = html
for k, v in tr_map.items():
    html_tr = html_tr.replace(k, v)

with open('index-tr.html', 'w', encoding='utf-8') as f:
    f.write(html_tr)

# AR TRANSLATIONS
ar_map = {
    'lang="en" dir="ltr"': 'lang="ar" dir="rtl"',
    'Incoming Travel Agency Turkey | Medical Tourism Istanbul': 'وكالة السفر والسياحة في تركيا | السياحة العلاجية في إسطنبول',
    'Plan Your Trip': 'خطط لرحلتك',
    'About': 'من نحن',
    'Services': 'خدماتنا',
    'Destinations': 'الوجهات',
    'Team': 'فريقنا',
    'Contact': 'اتصل بنا',
    'Your Trusted Partner<br />\n          <em>for Travel in Turkey</em>': 'شريكك الموثوق<br />\n          <em>للسفر في تركيا</em>',
    'Incoming tourism &amp; medical health tourism for visitors from the<br class="br-desktop" />\n          Middle East, Gulf region, and beyond — with a smile.': 'السياحة الوافدة والسياحة العلاجية للزوار من<br class="br-desktop" />\n          الشرق الأوسط، منطقة الخليج، وما وراءها — بابتسامة.',
    'Explore Our Services': 'استكشف خدماتنا',
    'Years of Experience': 'سنوات من الخبرة',
    'Tour Operators &amp; Direct': 'منظمي الرحلات ومباشر',
    'Primary Market Specialists': 'متخصصون في السوق الرئيسي',
    'Established 2005': 'تأسست عام 2005',
    'Over 20 years serving international visitors': 'أكثر من 20 عاماً في خدمة الزوار الدوليين',
    'Official TURSAB Member': 'عضو رسمي في تورساب',
    'License No. A-7468 — Fully certified &amp; regulated': 'ترخيص رقم A-7468 — معتمد ومنظم بالكامل',
    'Multilingual Team': 'فريق متعدد اللغات',
    'Support for Gulf &amp; Middle East visitors': 'دعم لزوار الخليج والشرق الأوسط',
    'Incoming Agency Only': 'وكالة سياحة وافدة فقط',
    '100% focused on welcoming visitors to Turkey': 'نركز 100% على الترحيب بالزوار في تركيا',
    'Guests Welcomed': 'الضيوف المرحب بهم',
    'Countries Served': 'الدول التي نخدمها',
    'Core Specialisations': 'تخصصاتنا الأساسية',
    'Who We Are': 'من نحن',
    'Your Smile is<br /><em>Our Mission</em>': 'ابتسامتك هي<br /><em>مهمتنا</em>',
    'Get in Touch': 'تواصل معنا',
    'Our Core Values': 'قيمنا الأساسية',
    'Openness &amp; Partnership': 'الانفتاح والشراكة',
    'We embrace the values and ideas of our partners and clients.': 'نحن نتبنى قيم وأفكار شركائنا وعملائنا.',
    'Teamwork at Heart': 'العمل الجماعي في صميمنا',
    'Management that leads by collaboration, not hierarchy.': 'إدارة تقود بالتعاون، وليس بالتسلسل الهرمي.',
    'Passionate Professionals': 'محترفون شغوفون',
    'A dedicated team working with skill and genuine care.': 'فريق متخصص يعمل بمهارة ورعاية حقيقية.',
    'Guests, Not Customers': 'ضيوف، وليسوا عملاء',
    'Every traveler is treated as a respected guest in our home.': 'يُعامل كل مسافر كضيف محترم في منزلنا.',
    'Attention to Detail': 'الاهتمام بالتفاصيل',
    'Maximum care at every step of the journey.': 'أقصى درجات العناية في كل خطوة من الرحلة.',
    'Guest Satisfaction First': 'رضا الضيف أولاً',
    'Your happiness is our highest achievement.': 'سعادتك هي أعلى إنجازاتنا.',
    'Always Adapting': 'نتكيف دائماً',
    'Striving for perfection and adapting to a changing world.': 'السعي للكمال والتكيف مع عالم متغير.',
    'Always Smiling': 'مبتسمون دائماً',
    'A positive spirit — even in challenging situations.': 'روح إيجابية — حتى في المواقف الصعبة.',
    'What We Offer': 'ماذا نقدم',
    'Three Pillars of<br />\n            <em>Expert Service</em>': 'ثلاث ركائز من<br />\n            <em>الخدمة الخبيرة</em>',
    'We arrange everything from A to Z so international guests can seamlessly arrive and enjoy Turkey.': 'نقوم بترتيب كل شيء من الألف إلى الياء حتى يتمكن الضيوف الدوليون من الوصول بسلاسة والاستمتاع بتركيا.',
    'Incoming Tourism &amp; Transportation': 'السياحة الوافدة والنقل',
    'From budget-friendly hotel reservations to luxury custom accommodation, we arrange everything you need to travel to Turkey from abroad. We offer 24/7 comfortable transport with chauffeured luxury vehicles or rent-a-car services, alongside private guided tours with expert local guides.': 'من حجوزات الفنادق الاقتصادية إلى الإقامة الفاخرة المخصصة، نلبي جميع الميزانيات. لتسهيل رحلتك، نقدم خيارات مركبات فاخرة مع سائق أو خدمات تأجير سيارات بدون سائق لنقل مريح على مدار الساعة. كما ننظم جولات خاصة برفقة مرشدين خبراء.',
    '24/7 VIP Transfers': 'نقل كبار الشخصيات على مدار الساعة',
    'Rent-a-car': 'تأجير السيارات',
    'Private Guided Tours': 'جولات خاصة مع مرشد',
    'Hotel Reservations': 'حجوزات الفنادق',
    'Local Guides': 'مرشدون محليون',
    'Custom Itineraries': 'مسارات مخصصة',
    'Plan Your Visit': 'خطط لزيارتك',
    'Medical &amp; Health Tourism': 'السياحة العلاجية والصحية',
    'We professionally manage your entire medical journey in collaboration with state-of-the-art hospitals. From initial referrals and certified interpretation to VIP accommodation and recovery, we ensure a seamless and dignified experience.': 'ندير رحلتك الطبية باحترافية بالتعاون مع مستشفيات مجهزة بأحدث التقنيات. من الإحالات والترجمة المعتمدة إلى إقامة كبار الشخصيات والتعافي.',
    'Hospital Referrals': 'إحالات المستشفيات',
    'High-Tech Clinic Partners': 'شركاء عيادات عالية التقنية',
    'Arabic Interpretation': 'الترجمة',
    'VIP Accompaniment': 'مرافقة كبار الشخصيات',
    'Patient Transfers': 'نقل المرضى',
    'Recovery Stays': 'إقامات التعافي',
    'Post-treatment Tours': 'جولات ما بعد العلاج',
    'Enquire About Medical Tourism': 'استفسر عن السياحة العلاجية',
    'Corporate Events &amp; MICE': 'أحداث الشركات والمؤتمرات',
    'For large-scale corporate organizations and international meetings, we provide A-to-Z professional planning and management. Every detail is meticulously planned to ensure your events are executed flawlessly.': 'للمنظمات المؤسسية الكبيرة والاجتماعات الدولية والأحداث المخطط لها بدقة، نقدم دعم التخطيط والإدارة الاحترافي من الألف إلى الياء.',
    'Event Planning': 'تخطيط الفعاليات',
    'International Meetings': 'الاجتماعات الدولية',
    'Corporate Organization': 'تنظيم الشركات',
    'VIP Protocol': 'بروتوكول كبار الشخصيات',
    'Ground Handling': 'الخدمات الأرضية',
    'Agency Partnerships': 'شراكات الوكالات',
    'Group Programs': 'البرامج الجماعية',
    'Trade Rates': 'أسعار تجارية',
    'Start Planning': 'ابدأ التخطيط',
    'Our primary markets': 'أسواقنا الرئيسية',
    'Where We Take You': 'إلى أين نأخذك',
    'Discover<br /><em>Turkey</em>': 'اكتشف<br /><em>تركيا</em>',
    'From the vibrant streets of Istanbul to the magical skies of Cappadocia — we know Turkey inside out.': 'من شوارع إسطنبول النابضة بالحياة إلى سماء كابادوكيا الساحرة — نحن نعرف تركيا جيداً.',
    'Flagship Destination': 'وجهتنا الرئيسية',
    'Culture, History &amp; the Bosphorus': 'الثقافة والتاريخ ومضيق البوسفور',
    'Imperial palaces, vibrant bazaars, private Bosphorus cruises, and world-class cuisine. The city where East meets West.': 'القصور الإمبراطورية، والأسواق النابضة بالحياة، ورحلات البوسفور الخاصة، والمأكولات العالمية.',
    'Discover Istanbul': 'اكتشف إسطنبول',
    'Must-See Wonder': 'عجائب لا بد من رؤيتها',
    'Balloons &amp; Fairy Chimneys': 'البالونات ومداخن الجنيات',
    'Rise with the sun in a hot air balloon over otherworldly landscapes. Underground cities, cave hotels, and unique scenery.': 'ارتفع مع الشمس في منطاد الهواء الساخن فوق مناظر طبيعية ساحرة. مدن تحت الأرض، فنادق الكهوف.',
    'Discover Cappadocia': 'اكتشف كابادوكيا',
    'Nature &amp; Serenity': 'الطبيعة والهدوء',
    'Lakes, Mountains &amp; Thermal Spas': 'البحيرات والجبال والينابيع الحرارية',
    'Peaceful lakeside retreats, thermal spas, and verdant mountain escapes just a short drive from Istanbul.': 'İstanbul\'dan kısa bir sürüş mesafesinde huzurlu göl kenarı inzivaları, termal kaplıcalar ve yemyeşil dağ kaçamakları.',
    'Discover Sapanca': 'اكتشف سبانجا',
    'The Green North': 'الشمال الأخضر',
    'Monasteries &amp; Black Sea Heritage': 'الأديرة وتراث البحر الأسود',
    'Ancient monasteries, lush highland plateaus, and the dramatic beauty of the Black Sea coast.': 'الأديرة القديمة، وهضاب المرتفعات الخصبة، والجمال الدرامي لساحل البحر الأسود.',
    'Discover Trabzon': 'اكتشف طرابزون',
    'Your Point of Contact': 'نقطة الاتصال الخاصة بك',
    'Meet the<br /><em>Team</em>': 'تعرف على<br /><em>الفريق</em>',
    'Real people, always available. Reach out directly to the right person for your needs.': 'أشخاص حقيقيون، متاحون دائماً. تواصل مباشرة مع الشخص المناسب لاحتياجاتك.',
    'Manager': 'المدير',
    'Sales': 'المبيعات',
    'Reservations': 'الحجوزات',
    'Contact Us': 'اتصل بنا',
    'Plan Your<br /><em>Journey to Turkey</em>': 'خطط لرحلتك<br /><em>إلى تركيا</em>',
    'Ready to start planning your trip? We handle all requests directly via WhatsApp to ensure you get the fastest, most personalized service.': 'هل أنت مستعد لبدء التخطيط لرحلتك؟ نحن نتعامل مع جميع الطلبات مباشرة عبر الواتساب لضمان حصولك على الخدمة الأسرع والأكثر تخصيصاً.',
    'Fast response from our dedicated team': 'استجابة سريعة من فريقنا المخصص',
    'Tailored itinerary — no templates': 'مسار مخصص — لا قوالب جاهزة',
    'English, Arabic &amp; Russian support': 'دعم باللغات الإنجليزية والعربية والروسية',
    'TURSAB certified — your guarantee': 'معتمد من تورساب — ضمانتك',
    'Message on WhatsApp': 'راسلنا على الواتساب',
    'Call': 'اتصل',
    'We\'re Online & Ready': 'نحن متصلون ومستعدون',
    'Skip the forms and email wait times. Chat directly with our dedicated team on WhatsApp for instant assistance and personalized travel planning.': 'تخطَ النماذج وأوقات الانتظار في البريد الإلكتروني. تحدث مباشرة مع فريقنا عبر الواتساب للحصول على مساعدة فورية وتخطيط سفر مخصص.',
    'Instant Responses': 'ردود فورية',
    'Personalized Care': 'عناية شخصية',
    'Priority Booking': 'أولوية الحجز',
    'Start WhatsApp Chat': 'ابدأ الدردشة على الواتساب',
    'Privacy Policy': 'سياسة الخصوصية',
    'Terms of Service': 'شروط الخدمة'
}

html_ar = html
for k, v in ar_map.items():
    html_ar = html_ar.replace(k, v)

with open('index-ar.html', 'w', encoding='utf-8') as f:
    f.write(html_ar)

print('Translated files updated successfully.')
